blank_issues_enabled: false
contact_links:
  - name: YIO Community Forum
    url: https://community.yio-remote.com/
    about: Please ask and answer questions here.
  - name: YIO Discord Channel
    url: http://chat.yio-remote.com/
    about: Chat with the community and for asking questions.
