name: Copy tranlsation master file
on: push
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copycat
      uses: andstor/copycat-action@v1.1.0
      env:
        DST_BRANCH: master
        DST_OWNER: YIO-Remote
        DST_REPO_NAME: tranlsations
        DST_PATH: remote-software/en_US.ts
        GH_PAT: ${{ secrets.GH_PAT }}
        SRC_BRANCH: dev
        SRC_PATH: translations/en_US.ts
        USERNAME: Workflow
        EMAIL: hello@yio-remote.com
