name: Copy translation files to translations repository
on: push
jobs:
  copycat:
    name: Copycat
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copycat
      uses: andstor/copycat-action@v1.1.0
      env:
        DST_BRANCH: dev
        DST_OWNER: YIO-Remote
        DST_REPO_NAME: remote-software
        DST_PATH: /translations/en_US.ts
        SRC_BRANCH: master
        SRC_PATH: /remote-software
        GH_PAT: ${{ secrets.GH_PAT }}
